server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.35.133:3306/hospital?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ylfqw
    password: ylfqw
  mvc:
    static-path-pattern: static/**
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.cykj.hospitalsystem.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.cykj.hospitalsystem.mapper : debug
